apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: ziwon/go-app
        ports:
        - containerPort: 8080
